/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as AppRouteImport } from './_app'
import { Route as AppIndexRouteImport } from './_app/index'
import { Route as AppStaffRouteImport } from './_app/staff'
import { Route as AppPermissionsRouteImport } from './_app/permissions'
import { Route as AppAnalyticsRouteImport } from './_app/analytics'
import { Route as AppTicketsIndexRouteImport } from './_app/tickets/index'
import { Route as AppOrganizationsIndexRouteImport } from './_app/organizations/index'
import { Route as AppTicketsTicketIdRouteImport } from './_app/tickets/$ticketId'
import { Route as AppOrganizationsOrganizationIdStaffRouteImport } from './_app/organizations/$organizationId/staff'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppPermissionsRoute = AppPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsIndexRoute = AppTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsIndexRoute = AppOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsTicketIdRoute = AppTicketsTicketIdRouteImport.update({
  id: '/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsOrganizationIdStaffRoute =
  AppOrganizationsOrganizationIdStaffRouteImport.update({
    id: '/organizations/$organizationId/staff',
    path: '/organizations/$organizationId/staff',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/permissions': typeof AppPermissionsRoute
  '/staff': typeof AppStaffRoute
  '/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/organizations/': typeof AppOrganizationsIndexRoute
  '/tickets/': typeof AppTicketsIndexRoute
  '/organizations/$organizationId/staff': typeof AppOrganizationsOrganizationIdStaffRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof AppAnalyticsRoute
  '/permissions': typeof AppPermissionsRoute
  '/staff': typeof AppStaffRoute
  '/': typeof AppIndexRoute
  '/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/organizations': typeof AppOrganizationsIndexRoute
  '/tickets': typeof AppTicketsIndexRoute
  '/organizations/$organizationId/staff': typeof AppOrganizationsOrganizationIdStaffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/permissions': typeof AppPermissionsRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/': typeof AppIndexRoute
  '/_app/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/_app/organizations/': typeof AppOrganizationsIndexRoute
  '/_app/tickets/': typeof AppTicketsIndexRoute
  '/_app/organizations/$organizationId/staff': typeof AppOrganizationsOrganizationIdStaffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/permissions'
    | '/staff'
    | '/tickets/$ticketId'
    | '/organizations/'
    | '/tickets/'
    | '/organizations/$organizationId/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/permissions'
    | '/staff'
    | '/'
    | '/tickets/$ticketId'
    | '/organizations'
    | '/tickets'
    | '/organizations/$organizationId/staff'
  id:
    | '__root__'
    | '/_app'
    | '/_app/analytics'
    | '/_app/permissions'
    | '/_app/staff'
    | '/_app/'
    | '/_app/tickets/$ticketId'
    | '/_app/organizations/'
    | '/_app/tickets/'
    | '/_app/organizations/$organizationId/staff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permissions': {
      id: '/_app/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AppPermissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets/': {
      id: '/_app/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AppTicketsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/': {
      id: '/_app/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AppOrganizationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets/$ticketId': {
      id: '/_app/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof AppTicketsTicketIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/$organizationId/staff': {
      id: '/_app/organizations/$organizationId/staff'
      path: '/organizations/$organizationId/staff'
      fullPath: '/organizations/$organizationId/staff'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdStaffRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppPermissionsRoute: typeof AppPermissionsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTicketsTicketIdRoute: typeof AppTicketsTicketIdRoute
  AppOrganizationsIndexRoute: typeof AppOrganizationsIndexRoute
  AppTicketsIndexRoute: typeof AppTicketsIndexRoute
  AppOrganizationsOrganizationIdStaffRoute: typeof AppOrganizationsOrganizationIdStaffRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppPermissionsRoute: AppPermissionsRoute,
  AppStaffRoute: AppStaffRoute,
  AppIndexRoute: AppIndexRoute,
  AppTicketsTicketIdRoute: AppTicketsTicketIdRoute,
  AppOrganizationsIndexRoute: AppOrganizationsIndexRoute,
  AppTicketsIndexRoute: AppTicketsIndexRoute,
  AppOrganizationsOrganizationIdStaffRoute:
    AppOrganizationsOrganizationIdStaffRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
